### ISSUE TITLE
Pidroid will not delete messages if swear words are edited in

### ISSUE THREAD

**Issue by rtobby-commits-tax-fraud** [JustAnyones/Pidroid#10]
When you write a message which doesn't contain any swearing, and then you edit the message to contain the swear word, Pidroid will not delete the message.
**Example:**
_Original message:_
cocl

_Edited message:_
cock

Pidroid will not delete the message even though it contains a word it would moderate. 

I am not entirely sure if Discord allows bots to view edited messages, but looking at how other bots do track edited messages in logs, Pidroid should be able to technically do it.

**Comment by JustAnyones** [comment]
Pidroid 5 has had swear detection removed as Discord implemented familiar feature natively.
