### ISSUE TITLE
An option to stop buildings from upgrading or changing, I get annoyed seeing the same building all over the city.

### ISSUE THREAD

**Issue by HunterAddams** [JustAnyones/Pidroid#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by erksmit** [comment]
i think you have the wrong place, these issues are for suggestions regarding pidroid. If you want to make a suggestion for theotown you should use Psuggest in the bot commands channel

**Comment by JustAnyones** [comment]
Correct.
