### ISSUE TITLE
No feedback when using reddit command when no credentials are provided in the config

### ISSUE THREAD

**Issue by erksmit** [JustAnyones/Pidroid#17]
When the bot does not have valid credentials for the reddit command, all queries for the command will result in "I could not find the specified subreddit!". Preferrably this message should be diffrent when there are no valid credentials to let the user know they didnt just spell the subreddit incorrectly.

**Comment by JustAnyones** [comment]
This problem should be alleviated by https://github.com/JustAnyones/Pidroid/commit/886c9e8154cebbf985b8fe0a718ed5f624909fe6
