### ISSUE TITLE
Automatic Timeout Timetable for personal usage of any person

### ISSUE THREAD

**Issue by yusuf8a684** [JustAnyones/Pidroid#23]
Ptimeout-timeable [start time] [ending time] [active: true, false] ["additional text when someone pings the user, it shows this text"]

examples: 
Ptimeout-timetable 7am 8pm true "I am at work, who cares anyways..."

Ptimeout-timetable 19pm 18pm false "h"

something like this I don't know

**Comment by erksmit** [comment]
Sounds like !afk, but with extra steps
