### ISSUE TITLE
Error when executing Preddit if specified subreddit doesn't exist

### ISSUE THREAD

**Issue by rtobby-commits-tax-fraud** [JustAnyones/Pidroid#32]
![image](https://user-images.githubusercontent.com/68446338/196517924-13f11b4f-98f8-459e-85c1-41f06557645a.png)
![image](https://user-images.githubusercontent.com/68446338/196518057-5315dd0e-e32b-441b-b3e0-44d1c1b41de1.png)

**Comment by JustAnyones** [comment]
Will be fixed by https://github.com/JustAnyones/Pidroid/commit/6efc1ab6073d42f6650b32d4692644d583a70213
