### ISSUE TITLE
Add a feature to edit suggestions after giving the command and give the user the ability to delete the suggestion 

### ISSUE THREAD

**Issue by rose-marly** [JustAnyones/Pidroid#34]
**Is your feature request related to a problem? Please describe.**
The ability to edit suggestions. Ex. I am frustrated when I did not type my suggestion.

**Describe the solution you'd like**
Give us the ability to edit the suggestions.

**Describe alternatives you've considered**
Give us the ability to delete the suggestion.

**Additional context**
I had suggestion on the discord server to create a Microsoft store version of TheoTown which is free but only inputted create a free version of the game. I can't edit the suggestion :, (

**Comment by rose-marly** [comment]
> Please update your feature request message filling in the areas below **bolded** text.

I did now, am new to github

**Comment by JustAnyones** [comment]
Editing on its own was not added. But you are now able to delete your own suggestion within 3 minutes of sending it.
