### ISSUE TITLE
Pheadpat

### ISSUE THREAD

**Issue by IlikeBurgerham** [JustAnyones/Pidroid#35]
Similar to Pbonk, it will show load an image/gif of a hand giving a peepo a headpat while showng the username mentioned.

use: Pheadpat @[username]

**Comment by JustAnyones** [comment]
Will be considered, it's a bit of a pain since I have to deal with Pillow library. In the meantime consider using ``Panimedia pat`` as an alternative.

**Comment by JustAnyones** [comment]
Under experimental creation https://github.com/JustAnyones/Pidroid/commit/2dbf6db80bee87abec5462486027c37a30f23da1
