### ISSUE TITLE
Suggestion to remove Pcovid command

### ISSUE THREAD

**Issue by PBbunnypower** [JustAnyones/Pidroid#38]
Pcovid command doesnt work anymore and returns as corrupted data. The website the error message leads to doesnt exist anymore. I find that when it worked as well that the recent "data" was outdated and difficult to believe compared to actual current statistics. Plus the threat of covid is minimal and I do not find the channel to be so useful. I theorize that people only use the channel because it exists and for the sake of using it or to test it. 

I suggest it would be best to delete the channel and to remove the command.

**Comment by JustAnyones** [comment]
The channel has been removed. As for the command, it will be removed when API stops working completely.
