### ISSUE TITLE
Allow users to change XP square color in rank menu

### ISSUE THREAD

**Issue by rtobby-commits-tax-fraud** [JustAnyones/Pidroid#39]
I believe it would be cool to configure the color of the squares (or maybe even choose a different emoji?) in the rank menu (displayed in image).
![image](https://github.com/JustAnyones/Pidroid/assets/68446338/a4244934-38c2-4b8b-9bd0-132e9c22dfb3)
Example:
By default, Pidroid will display XP bar like this:
🟦🟦🟦🟦🟦⬛⬛⬛⬛⬛
However, you would be able to change the color to
🟧🟧🟧🟧🟧⬛⬛⬛⬛⬛
🟩🟩🟩🟩🟩⬛⬛⬛⬛⬛
🟥🟥🟥🟥🟥⬛⬛⬛⬛⬛
using some command like `Prank customize <color>` or something like that ¯\_(ツ)_/¯

**Comment by PBbunnypower** [comment]
And purpleee

**Comment by JustAnyones** [comment]
First, I think I'll change command name from Prank to something else to not occasionally collide with the word prank. As for customization, are you suggesting this be a server wide setting or a member specific one instead?
