### ISSUE TITLE
Prole-info command

### ISSUE THREAD

**Issue by rtobby-commits-tax-fraud** [JustAnyones/Pidroid#7]
Since we already have Pui and Psi, I don't see a reason _not_ to add a command for role information. The command could display the role's name, color, icon (if there's one), ID, permissions, etc.
Since we are allowed to copy role IDs, searching for them shouldn't be hard.
Alias: `ri`, `roleinfo`, `role`
Command: `Prole-info <role name or id>`

**Comment by JustAnyones** [comment]
Command has been partially implemented by https://github.com/JustAnyones/Pidroid/commit/8dd8c15cb0ce65514f42ce4017064ce9737a855c

The icon features are not available as I have not yet implemented the methods to obtain it from the d.py library

**Comment by JustAnyones** [comment]
Fully implemented by https://github.com/JustAnyones/Pidroid/commit/9d723d0b28a22abc8b959b54edfeae90f47c15d9
